ringcentral/engage-digital-api-docs

specs/engage-digital_openapi3.yaml

Adding documentation for new endpoint we are currently developing.
A few remarks on POST and PUT requests : 
- We might want to specify that some params (eg: L5204-L5221) can be used several times.
- We might want to explain about the orders of the params :
A request with params
name:Cap
channels[][channel_id]:id_1
channels[][default_capacity]:1
channels[][max_capacity]:2
channels[][channel_id]:id_2
channels[][default_capacity]:1
channels[][max_capacity]:10
And with params (just switching orders) :
name:Cap
channels[][channel_id]:id_1
channels[][channel_id]:id_2
channels[][default_capacity]:1
channels[][max_capacity]:2
channels[][default_capacity]:1
channels[][max_capacity]:10
Will NOT yield the same results (actually the second one will be rejected).
I tried to mention it on the …

Feature: Add OpenAPI3 doc for user_capacities endpoint.

---

specs/engage-digital_openapi3.yaml

Make variables url follow openapi spec for better website generation #19
hostname is not enum to support more than just prod.
Pity it does not work in editor.swagger.io because of CORS headers (it's intentional as I don't want to incentivize people to use global api token in the browser but it's a bit painful for this particular usecase.
Could not test bearer because of that

api: add variables to endpoint url of openapi spec, fixes #19

---

docs/webhooks/events.md

Hello,
I updated the task webhooks documentation to add the `task.recategorized` event
I also used this opportunity to:
- add the missing task metadata fields to the documentation
- get rid of the UUID mention (all "xxx_id" fields are BSON ids, we could consider them as UUID but it seems String is mostly used so lets be consistent)
- fix the domain_id field which is also a BSON Id not an Integer

Add task.recategorized webhook + complete task webhook documentation

---

package-lock.json
specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Status API currently doesn't include filter parameters when fetching all users while there are some
- source_ids
- category_ids
- team_ids
- spoken_languages
also updated postman collection

Better: Add filter parameters to Status API

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

This PR adds documentation for the new endpoint to update credentials of email sources for imap/smtp adapters.
**Please, don't merge it until the feature MR is merged.**

Add documentation for email credentials updating. RD-18084

---

README.md

We missed the `mdx_include` package that's needed to run the mkdocs server. so I've added it and joined all pip dependencies installation into a single line command.

Add `mdx_include` to the mkdocs installing documentation

---

code-samples/interactions/threads.js
code-samples/interactions/threads.php
code-samples/interactions/threads.py
code-samples/interactions/threads.rb
docs/interactions/quick-start.md

PR has important changes in the quick start guide, the URL for the server was obsolete and docs were missing information on how to find one's sub-domain information. I've updated both of those in this code change.

Updated Quick Start Guide with correct URL in sample code and docs

---

docs/interactions/structured-messages/select.md
docs/interactions/structured-messages/template.md

In RD-19682 we introduced new adaptation that truncates text fields if they exceed the UTF-16 code units max count because WhatsApp has slightly different validation.
This MR updates the documentation to keep it up to date.

Feature: add info about UTF-16 code units adaptation in WhatsApp

---

docs/interactions/structured-messages/select.md

In RD-19050 we extended the sections validation from WhatsApp List Message to ABC List Picker to make it more consistent and stable. This MR is to update the ABC API limits documentation.

Feature: update docs for Apple Business Chat List Picker sections validations. RD-19050

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Hey !
Ticket(s):
* [RD-19829](https://jira.ringcentral.com/browse/RD-19829)
Change(s):
* Add Surveys endpoint doc
I Merged survey_response and surveys into the same section, this is debatable as it's not the same url, but it was clearer doc-wise. If you disagree, I can make it into to two separate sections. Discussion on the subject [here](https://github.com/ringcentral/engage-digital-api-docs/pull/52#discussion_r746791601) in the comments below
Ping @CedricBm PR is ready for review

Feature: Add Surveys API endpoint documentation. RD-19829

---

specs/engage-digital_openapi3.yaml

Add fields to schema
Nothing to update for postman
Preview from swagger editor:

Better: Add surveys extension related fields to intervention schema. RD-20478

---

specs/engage-digital_openapi3.yaml

Remove deprecated fields that will be removed on 2021 December 15th
Schema changes don't affect postman collection so there's no update to postman JSON file

Better: Remove deprecated fields from doc. RD-19828

---

docs/interactions/structured-messages/list.md

Removes body from the attributes since customer should use `structured-content.title`
Specify truncate to 512 chars on title since API allows 1024

Better: ABC List - Add adaptation on title and remove mention of body RD-20087

---

specs/engage-digital_openapi3.yaml

As explained in https://github.com/ringcentral/engage-digital-api-docs/pull/71#issuecomment-1057602813 we need to add topologies to the x-tag-group to have it visible in the website navigation menu

Add: Topologies to x-tag-groups (left navigation menu on the website) RD-21094

---

docs/digital/exports/main-export-fields.md
specs/engage-digital_openapi3.yaml

We should update the documentation because we added synchronization_status and synchronization_error_custom fields in the messages export and API
**Export**:
**API**:

Better: Add synchronization_status and synchronization_error fields to export messages documentation. RD-20491

---

specs/engage-digital_postman2.json

I've just run posman generation. Looks like in https://github.com/ringcentral/engage-digital-api-docs/commit/dec1e4ebede918054dd8cc8bb9e84eec835d55d1, it was missed.

Better: Regenerate postman for Topologies. RD-21094

---

Dockerfile
README.md
preview.sh

I always get tricked because my computer still has python2 as default and instructions for this projects require python3
I made a little script that can launch a preview with docker directly by just running `./preview.sh`

Minor: Add a little script to launch preview with docker. RD-23147

---

.github/workflows/test.yaml

We are getting the following error on CI runs:
```
Run go install github.com/grokify/spectrum@latest
go: downloading github.com/grokify/spectrum v1.12.6
go: downloading github.com/grokify/mogo v0.40.5
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/getkin/kin-openapi v0.106.0
go: downloading github.com/grokify/gocharts/v2 v2.8.2
go: downloading golang.org/x/sys v0.0.0-20221013171732-95e765b1cc43
go: downloading github.com/invopop/yaml v0.2.0
go: downloading github.com/xuri/excelize/v2 v2.6.1
go: downloading github.com/valyala/quicktemplate v1.7.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading gonum.org/v1/gonum v0.12.0
go: downloading …
```

CI: Fix build with go 1.18

---

.github/workflows/test.yaml

The [CI fail](https://github.com/ringcentral/engage-digital-api-docs/actions/runs/3742186678/jobs/6353590187) because, in the latest version of [spectrum](https://github.com/grokify/spectrum), the generated postmark file is different that previous version. I fixed the version of spectrum used to the latest version compatible with of [engage-digital_postman2.json](https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/engage-digital_postman2.json).

Fix spectrum version in CI

---

specs/Dockerfile
specs/README.md
specs/gen_postman.sh

Little script to generate de postman from the open api spec. I used it in https://github.com/ringcentral/engage-digital-api-docs/pull/136/files and it works well

Minor: Add script to generate postman from open api specs. RD-25672

---

docs/webhooks/events.md

https://jira.ringcentral.com/browse/RD-25451
This PR adds a `source_type` field to the content webhook events.

Better: Add source_type to content events. RD-25451

---

docs/digital/exports/main-export-fields.md

Added `ig_followers_count` field to list of exported fields for Identity model.

Minor: Add ig_followers_count to list of fields in identity export. RD-26034

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-26088
This PR updates the doc to add the `POST /identities/import endpoint`.
I updated `specs/engage-digital_openapi3.yaml` and then generated `specs/engage-digital_postman2.json` from it using spectrum (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

Feature: Add POST /identities/import endpoint. RD-26088

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-26395
This PR updates the doc to add the `PUT /identity_groups/:id/merge` endpoint.
I updated `specs/engage-digital_openapi3.yaml` and then generated `specs/engage-digital_postman2.json` from it using spectrum (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

Feature: Add PUT /identity_groups/:id/merge endpoint. RD-26395

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Add the color_hex to api documentation for sources:

Minor: Add color_hex to sources API. RD-26458

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-26433
This PR updates the doc to add the `source_id` param to the `GET /identities` endpoint.
I updated `specs/engage-digital_openapi3.yaml` and then generated `specs/engage-digital_postman2.jso`n from it using spectrum (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

Feature: Add source_id param to GET /identities. RD-26433

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-26589
This PR updates the doc to add the `common_ancestors_threading` field to the content sources API.
I updated specs/engage-digital_openapi3.yaml and then generated specs/engage-digital_postman2.json from it using spectrum (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

Feature: Add common_ancestors_threading to content sources API. RD-26589

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-27142
This PR updates the doc to add the read_only field to the custom fields API.
I updated specs/engage-digital_openapi3.yaml and then generated specs/engage-digital_postman2.json from it using spectrum (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

Minor: Add the read_only field to the custom field api RD-27142

---

specs/engage-digital_openapi3.yaml

Better: Add email headers API. RD-27006

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-27341
This PR updates the doc to add the identity_group_ids filters to the identities API.
I updated specs/engage-digital_openapi3.yaml and then generated specs/engage-digital_postman2.json from it using spectrum (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

API: Allow to filter /1.0/identities by identity_group_ids RD-27341

---

docs/interactions/structured-messages/apple-auth.md

Changed: current Auth message
* Changes success status to "success" instead of "authenticated"
* includes the version in the response
New: new Auth message
* adds distinction with v1
* includes new payload

Better: Update Apple Authenticate message specifications RD-24033

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-27746
his PR updates the doc to add the thread_category_ids params to the /bots/handover endpoint.
I updated specs/engage-digital_openapi3.yaml and then generated specs/engage-digital_postman2.json from it using spectrum (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

API: Add thread_category_ids params to /bot/handover endpoint RD-27746

---

docs/sdks/source-sdk/objects.md

**Ticket(s)**:
- [RD-28559](https://jira.ringcentral.com/browse/RD-28559)
**Change(s)**:
- Add `content_id`/`retry` fields to Channel SDK documentation
- Remove non-existent fields from documentation

Better: Add retry/content_id to Channel SDK documentation. RD-28559

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Better: Add the permission filter documentation of the content_sources API. RD-28779

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-29347
This PR updates the doc to specify that the email search is case-insensitive in the users API.
I updated `specs/engage-digital_openapi3.yaml` and then generated `specs/engage-digital_postman2.json` from it using the `./gen_postman.sh` script (cf. https://github.com/ringcentral/engage-digital-api-docs/blob/master/specs/README.md#usage).

Better: Case insensitive email filtering on GET users API. RD-29347

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

This MR adds documentation for the new status filter on GET /interventions.
It's my first MR in this project so let me know if I'm doing it wrong.
Swagger:
Postman

Better: Add status filter on /interventions RD-29246

---

docs/interactions/index.md

PLD-1840 Changed 'Engage' product name to 'RingCX', eliminated product naming where possible, and minor fixes

Update index.md Changed 'Engage' product name to 'RingCX', eliminated product naming where possible, and minor fixes

---

specs/engage-digital_openapi3.yaml

Add identity_group_id to contents:
Add identity_group_id to interventions:

API: Add identity_group_id into interventions and contents api RD-28788

---

.markdownlint-cli2.cjs
.markdownlint/customRules/rules/code-samples.js
.markdownlint/rules/ci.cjs
.markdownlint/rules/index.cjs
.markdownlint/rules/vscode.cjs

ADD a new rule which validates existence of Code samples.
This rule will search for pattern `{!> ... !}` and check if the reference file specified exists.

Linter: New Rule (DPW005) for Code Samples

---

.github/workflows/test.yaml
specs/README.md

I had some trouble to install go and have the exact same result that the one produced by the CI with :
```
$ ~/go/bin/spectrum --config engage-digital_postman2.config.json --basePostmanFile engage-digital_postman2.base.json --openapiFile engage-digital_openapi3.yaml --postmanFile engage-digital_postman2.json
```
For example : https://github.com/ringcentral/engage-digital-api-docs/actions/runs/9391479723/job/25863719761
I tried to update go and modules versions, but I had trouble to make tests working.

Clarify the README to generate the Postman file.

---

specs/engage-digital_openapi3.yaml

Add the new response to make the clients aware that if they try to spam the PUT route, they can receive a 409 because the ressource will be locked while the 1st operation is being processed.

Improvement: Add the new 409 response documentation reflecting the addition of a cache_lock on PUT /1.0/identity_groups/:id . RD-24154

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

In this MR we add the thread_category_ids parameters to the bot API complete endpoint.

Add thread_category_ids to bot API complete endpoint RD-30684
