ringcentral/engage-digital-api-docs

docs/sdks.md

Consistency around JavaScript, and properly capitalizing WordPress.

Update camel casing in SDK documentation

---

specs/README.md
specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Just a little fix. Successfully tested on https://editor.swagger.io/

Fix OpenAPI spec typo & fix postman spec generation doc

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

We forgot to update the doc for `ask_an_expert` feature. 
I generated a postman via related command.

Minor: Add ask_an_expert and escalate_to_video roles.

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Add these new fields in the GET and PUT /content_sources
- live_chat
- enable_android
- enable_ios
- enable_web

Better: Add features scope fields on EM sources.

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

https://jira.ringcentral.com/browse/RD-18147

Better: Suffix every array params by `[]`. RD-18147

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

This PR adds doc about the new route to get user interface locales list.

Add /interface_locales path from RD-17485

---

docs/interactions/structured-messages/apple-auth.md
docs/interactions/structured-messages/apple-pay.md
docs/interactions/structured-messages/carousel.md
docs/interactions/structured-messages/rich-link.md
docs/interactions/structured-messages/select.md
docs/interactions/structured-messages/template.md
docs/interactions/structured-messages/time-select.md
docs/sdks/source-sdk/structured-messages.md

* Jira Ticket : https://jira.ringcentral.com/browse/RD-18781

Update documentation about the support of private attachments for GBM and Facebook Messenger. RD-18781

---

specs/engage-digital_openapi3.yaml

Only schema changes so no need to update postman file.

Better: Remove legacy field from interventions schema. RD-20480

---

docs/interactions/structured-messages/apple-auth.md
docs/interactions/structured-messages/apple-pay.md
docs/interactions/structured-messages/index.md
docs/interactions/structured-messages/list.md
docs/interactions/structured-messages/rich-link.md
docs/interactions/structured-messages/select.md
docs/interactions/structured-messages/time-select.md
docs/interactions/structured-messages/webview.md
docs/sdks/index.md

- Replaced mentions of "Apple Business Chat" with "Apple Messages for Business"

Minor: Rename mentions of Apple Business Chat to Apple Messages for Business RD-21568

---

specs/engage-digital_openapi3.yaml

Hey !
Ticket(s):
* RD-22624
Change(s):
* Added Source params for GET /1.0/content_sources : `template_messages` and `hsm_template`
* Added Contents params for POST /1.0/contents : `template_name` and `template_language`
* Added WA source in `to` param description for POST /1.0/contents

Better: Added doc for WA Outbound. RD-22624.

---

.github/workflows/test.yaml
specs/engage-digital_openapi3.yaml

Here is an example of how the test works:

CI: Ensure postman example are updated. RD-23144

---

docs/interactions/structured-messages/rich-link.md

Minor: Update doc about restriction on ABM bid. RD-23235

---

docs/webhooks/events.md
specs/engage-digital_openapi3.yaml

We are adding capabilities_supported for all contents to the API and webhooks so we reflect the info here

Better: Add capabilities_supported for contents in API and webhooks. RD-23140

---

specs/engage-digital_openapi3.yaml

This  will displayed on 4 endpoints for source (2 GET and 2 PUT)

Minor. Update api doc about source regarding json response for auto_responses, signatures and from_name. RD-23635

---

specs/engage-digital_openapi3.yaml

This will be displayed on 4 endpoints for source (2 GET and 2 PUT)

Minor. Update api doc about source regarding json response for email fields. RD-23635

---

docs/sdks/source-sdk/objects.md

**JIRA ticket(s)**:
- [RD-24454](https://jira.ringcentral.com/browse/RD-24454)
Pretty straightforward, in [RD-24453](https://jira.ringcentral.com/browse/RD-24453) I added the filename into the attachment serialization for request sent by ED so I'm updating the documentation accordingly

Minor: Add attachment filename into payload sent by ED. RD-24454

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_openapi3_ngdoc.yaml

**Ticket(s)**:
- [RD-24861](https://jira.ringcentral.com/browse/RD-24861)
**Change(s)**:
- Fix registerable events list in webhook api

Better: Fix available events list for webhooks. RD-24861

---

docs/interactions/chatbots/replies.md
specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

This PR updates the doc mentioning contents creation to uses booleans for the `private` field instead of using "0" and "1".

Minor: Use booleans for the private content's field. RD-25285

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Cf. https://jira.ringcentral.com/browse/RD-25403
I updated reference spec (engage-digital_openapi3.yaml) and generated engage-digital_postman2.json with spectrum.

Better: [Customer SLA Indicator] Granularity by Category in Sources API Doc. RD-25403

---

specs/engage-digital_openapi3.yaml

Fix: Post on interventions returns only an intervention. RD-25545

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Better: Add POST bots/engage API. RD-25046

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Better: Add POST bots/complete API. RD-25065

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Better: add close_thread to the /bots/complete API. RD-25373

---

.markdownlint-cli2.cjs
.markdownlint/customRules/helpers/addError.js
.markdownlint/customRules/helpers/filterTokens.js
.markdownlint/customRules/helpers/index.js
.markdownlint/customRules/rules/html-images.js
.markdownlint/customRules/rules/html-links.js
.markdownlint/customRules/rules/md-images.js
.markdownlint/customRules/rules/md-links.js
.markdownlint/rules/index.cjs
docs/interactions/index.md
docs/interactions/structured-messages/index.md
docs/interactions/web-messaging/index.md
docs/sdks/source-sdk/request-response.md
docs/sdks/survey-sdk/index.md

1. Add Markdown Linter Setting Files
2. Fix Some Linter Issues

ADD Markdown Linter

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Minor: Update status api (agent can change own status). RD-25846

---

docs/sdks/source-sdk/action-details.md
docs/sdks/source-sdk/options.md

**Ticket(s)**:
- [RD-25947](https://jira.ringcentral.com/browse/RD-25947)
**Change(s)**:
- Add documentation about the `messaging.queuing_update` option
- Add documentation about the `messaging.queuing_update` action
**Screenshots**:
<br/>

Better: Add documentation about Channel SDK queuing update. RD-25947

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

**Ticket(s)**:
- [RD-26991](https://jira.ringcentral.com/browse/RD-26991)
**Change(s)**:
- Update Folders API documentation

Better: Add documentaiton about Search folders availability in Folders API. RD-26991

---

specs/gen_postman.sh

Before:
docker: Error response from daemon: create .: volume name is too short, names should be at least two alphanumeric characters.
After:
wrote Postman collection [engage-digital_postman2.json]

Minor: Fix gen postman script. RD-27119

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

API: allow to filter /1.0/categories by ids. RD-27139

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

API: allow to filter /1.0/tags by ids. RD-27533

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

API: Revert Add get intervention segment. RD-27899

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

API: Allow to filter /1.0/identity_groups by ids RD-27908 

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

Better: Add active state filter for content_sources API. RD-28879

---

docs/index.md

Update index.md to remove Engage/Engage Digital/ED occurrences where possible, and otherwise replace them with RingCX    as a new product name.
Please review and comment if required.

Update index.md to remove Engage/Engage Digital/ED occurrences

---

docs/digital/exports/main-export-fields.md

**Ticket(s)**:
- [RD-29472](https://jira.ringcentral.com/browse/RD-29472)
**Change(s)**:
- The list of available events was not available to our clients as of yet, this PR aims to document them all in one place as of April 2024.

Better: Add the list of available events in the Events export documentation. RD-29472

---

docs/sdks/survey-sdk/realtime-responses-import.md

'Engage' product name is replaced with 'RingCX'

Update realtime-responses-import.md 'Engage' product name is replaced with 'RingCX'

---

docs/interactions/web-messaging/index.md

PLD-1840 Changed 'Engage' product name to 'RingCX'

Update index.md Changed 'Engage' product name to 'RingCX'

---

docs/interactions/quick-start.md

PLD-1840 Changed 'Engage' product name to 'RingCX'

Update quick-start.md Changed 'Engage' product name to 'RingCX'

---

docs/sdks/ui-embed/events.md

https://jira.ringcentral.com/browse/RD-17237
- Removes references to redirect_to_login_when_embedded_disabled as we are removing this feature flag.

Minor: Remove references to redirect_to_login_when_embedded_disabled RD-17237

---

docs/webhooks/events.md

This adds the 3 new webhooks to the documentation

Add new content.thread_* webhooks RD-29320

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

**Ticket(s)**:
- [RD-29591](https://jira.ringcentral.com/browse/RD-29591)
**Change(s)**:
- Add doc about `/1.0/users/:user_id/sources_permissions`
**ToDo(s)**:

Better: Add /1.0/users/:user_id/sources_permissions documentation. RD-29591

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_postman2.json

This PR add the trigger parameter to the Bot API handover endpoint

API: Add trigger into bot handover api endpoint RD-29540

---

docs/interactions/web-messaging/chat-targeting.md

- Rename hour condition to time
- Change its format from number to HH:MM
- Add new values range and interval
- Update examples

Improvement: Update hour condition documentation to match its new name and format. RD-30511

---

docs/sdks/source-sdk/quick-start.md

**Ticket(s)**:
- [RD-31219](https://jira.ringcentral.com/browse/RD-31219)
**Change(s)**:
- Remove mention to file size limit on Channel SDK

Minor: Remove mention to file size limit on Channel SDK. RD-31219

---

docs/webhooks/events.md

user_id updated to include the specific case of it not being included in task.recategorized webhook

Minor: Explicit that no user_id is included on event task.recategorized RD-32819

---

specs/engage-digital_openapi3.yaml
specs/engage-digital_openapi3_ngdoc.yaml
specs/engage-digital_postman2.json

Add 2 new fields to the Contents API.
Generate postman to update the collection .

Minor: Add rated_with and rated_reason to Contents API. RD-36456

---

docs/digital/exports/main-export-fields.md

This PR adds identity list events to the documentation.

Better: Add identity list events. RD-36459
